name: fintechdemo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 '


dependencies:
  flutter:
    sdk: flutter
  #firebase_auth:
  #firebase_databse:

  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/

